### ISSUE TITLE
Missing splash2.jpg and a few dependencies in the readme

### ISSUE THREAD

**Issue by smartbrain** [baldurodinsson/auroracoin-project#2]
Can't compile as it is missing res/images/spash2.jpg

Also readme is missing a few dependencies

In addition to

```
First, make sure that the required packages for Qt4 development of your
distribution are installed, for Debian and Ubuntu these are:

::

    apt-get install qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev \
        libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev \
        libssl-dev libdb4.8++-dev
```

you also need libminiupnpc-dev and libminiupnpc8 for it to compile for a while (until it hits the splash2.jpg error)

**Comment by kosmoplovci** [comment]
have the same problem with res/images/splash2.jpg missing (linux/ubuntu12.04).

havent checked with dependencies, seems i have all that is needed already, as i already compiled many recent altcoin clients already, but you may be right on that.

**Comment by baldurodinsson** [comment]
This seems to be related to the file extension, the file is there but has a .JPG extension instead of .jpg. You are probably compiling on a case sensitive system. Will get on this.

**Comment by kosmoplovci** [comment]
yes you are right, it is a case sensitivity problem which is very important on linux. when renamed/copied file it compiled through, so just change it in repo and issue is fixed for all :)
